--- 
clone: 
  depth: 1
kind: pipeline
name: ZyCPipeline
concurrency:
  limit: 6
steps: 
  - 
    commands: 
      - "bash do-now.sh"
    environment: 
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      GIT_SECRET:
        from_secret: GIT_SECRET
    image: zycromerz/kerneldocker:v2
    name: ZyC-TWRP
    trigger: 
      branch: 
        - unified-tes