name: Compile TWRP

on: [push]

jobs:
  build:

    runs-on: zycromerz/kerneldocker:v2

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        ls
        chmod a+x do-now.sh
        bash do-now.sh